### ISSUE TITLE
Dependencies out of sync

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity-seed#43]
Hello,

After fresh clarity-seed download, `npm install` finishes with these errors:

```
npm ERR! peer dep missing: @angular/compiler@~2.2.0, required by codelyzer@1.0.0-beta.4
npm ERR! peer dep missing: @angular/core@~2.2.0, required by codelyzer@1.0.0-beta.4
npm ERR! peer dep missing: tslint@^3.9.0, required by codelyzer@1.0.0-beta.4
```

Then `npm run lint` produces these errors:
```
Users/jinnie/workspace/test/clarity-seed/node_modules/tslint/lib/runner.js:118
            throw error;
            ^

Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jinnie/workspace/test/clarity-seed/node_modules/codelyzer/selectorNameBase.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! clarity-seed@0.8.0 lint: `tslint "src/**/*.ts"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clarity-seed@0.8.0 lint script 'tslint "src/**/*.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the clarity-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint "src/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs clarity-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls clarity-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jinnie/workspace/test/clarity-seed/npm-debug.log

```

After manual update of codelyzer to 2.0.1, the following errors occur:
```
Could not find implementations for the following rules specified in the configuration:
    label-undefined
    no-duplicate-key
    no-unreachable
    directive-selector-prefix
    component-selector-prefix
    directive-selector-name
    component-selector-name
    directive-selector-type
    component-selector-type
```
Obviously some core tslint rules have been changed or deprecated.

I tried downgrading the tslint, but this leads to endless cycle of unmet dependencies.
I guess it would be better to update the tslint and codelyzer to newer versions (avoiding the angular 4 requiring betas), and update the list of tslint rules.

Best regards!

**Comment by Shijir** [comment]
Hi @Jinnie, are you still seeing this issue? And is it happening in the master branch? Also, if you have cloned `clarity-seed` and pulled down multiple branches, make sure you are doing a fresh install (remove `node_modules` directory and run `npm install` or `yarn`) every time you switch the branches as each branch uses different dependencies or different versions of the same dependency.

**Comment by Jinnie** [comment]
Not anymore.
Good job, @Shijir, @jeeyun
The recent update of dependencies has fixed the issue.
Thanks
